permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments


gems: [jekyll-paginate]
paginate: 2 #6
comments: true
paginate_path: "/page/:num"

destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Dominique Clarke
description: Junior Front-end Developer
email: dominiquedclarke@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com"
url: "http://dominiqueclarke.github.io/portfolio"
repository: "https://github.com/dominiqueclarke/portfolio"
disqus_shortname: 
google_analytics: 

# social footer
social:
  github:
    slug: github
    link: http://github.com/nandomoreirame
  facebook:
    slug: facebook
    link: http://facebook.com/fernando.dev
  twitter:
    slug: twitter
    link: http://twitter.com/nandomoreirame
  instagram:
    slug: instagram
    link: http://instagram.com/nandomoreira.me
  linkedin:
    slug: linkedin
    link: http://linkedin.com/in/nandomoreirame