permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments


gems: [jekyll-paginate]
paginate: 2 #6
comments: true
paginate_path: "/page/:num"

destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Dominique Clarke
description: Junior Front-end Developer
email: dominiquedclarke@gmail.com
baseurl: "/portfolio/"
url: "http://dominiqueclarke.github.io"
repository: "https://github.com/dominiqueclarke"
disqus_shortname: 
google_analytics: 

# social footer
social:
  github:
    slug: github
    link: http://github.com/dominiqueclarke
  facebook:
    slug: facebook
    link: http://facebook.com/waydiesel
  twitter:
    slug: twitter
    link: http://twitter.com/deeclarkesays
  linkedin:
    slug: linkedin
    link: http://linkedin.com/in/dominiqueclarke